# Configurações de PRODUÇÃO para Render
server:
  port: ${PORT:8084}
  max-http-header-size: 50MB

# YouTube API Configuration
youtube:
  api:
    key: ${YOUTUBE_API_KEY:YOUR_API_KEY_HERE}
  
spring:
  application:
    name: equilibrium-mcp-video

  ai:
    mcp:
      server:
        protocol: SSE
        name: youtube
        version: 1.0.0
        type: SYNC
        instructions: "MCP Server with YouTube Data API v3 integration for personalized video recommendations based on user profile"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

# Logging otimizado para produção
logging:
  level:
    root: INFO
    com.equilibrium: DEBUG
    org.springframework.web: WARN
    com.google.api.client.http: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management e Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
